version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "CiscoProject"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-o0os7zp8nz28"
s3_prefix = "CiscoProject"
region = "us-east-1"
profile = "root"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
